#!/bin/bash

function update_ca() {
  echo "Updating CA certificates..."
  cp "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}"
  update-ca-certificates --fresh >/dev/null
}

function ensure_ownership_permissions() {
    if [ -d ${HOME:-/var/lib/gitlab-runner}/.gnupg ]; then chmod 700 ${HOME:-/var/lib/gitlab-runner}/.gnupg; fi
    if [ -f ${HOME:-/var/lib/gitlab-runner}/.ssh/id_rsa ]; then chmod 600 ${HOME:-/var/lib/gitlab-runner}/.ssh/id_rsa; fi

    if [ -f /var/run/docker.sock ]; then
        sudo chown root:docker /var/run/docker.sock
        sudo chmod 660 /var/run/docker.sock
    fi
}


# gitlab-runner's config file
CONFIG_FILE=${CONFIG_FILE:-${CONFIG_DIR}/config.toml}

# init home directory
if [[ ! -L "${HOME:-/var/lib/gitlab-runner}" ]] && [ ! -d "${HOME:-/var/lib/gitlab-runner}/builds" ]; then
    if [ ! -d "${HOME:-/var/lib/gitlab-runner}" ]; then
        sudo mkdir -p "${HOME:-/var/lib/gitlab-runner}";
    fi
    sudo cp -pr /home/ubuntu/. ${HOME:-/var/lib/gitlab-runner}/
    sudo chown -R 1000:1000 ${HOME:-/var/lib/gitlab-runner}
fi


ensure_ownership_permissions
if [ -f ${HOME}/.profile ]; then source ${HOME}/.profile; fi


if [ "${1:0:1}" != '/' ]; then
    # custom certificate authority path
    CA_CERTIFICATES_PATH=${CA_CERTIFICATES_PATH:-${CONFIG_DIR}/certs/ca.crt}
    LOCAL_CA_PATH="/usr/local/share/ca-certificates/ca.crt"

    if [ -f "${CA_CERTIFICATES_PATH}" ]; then
      # update the ca if the custom ca is different than the current
      cmp --silent "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}" || update_ca
    fi

    while sleep 1m; do ensure_ownership_permissions; done &
    # launch gitlab-ci-multi-runner passing all arguments
    exec sudo gitlab-ci-multi-runner "$@"
    kill %1
else
    exec "$@"
fi
